<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIVision.Application\AIVision.Application.csproj" />
    <ProjectReference Include="..\AIVision.Domain\AIVision.Domain.csproj" />
  </ItemGroup>

</Project>
